### ISSUE TITLE
Convo: When targeting and entering a convo, the black bars remain, and disappear when you release target

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#101]
When targeting and entering a convo, the black bars remain, and disappear when you release target

Repro:
Go to level "02-2-Sewer-TrainingChamber"
Target the first dummy (do not let go of target)
Hit the dummy, this will force you into a convo
The black target bars will be present in the convo.
Release the target button.
The Black bars will disappear.

**Comment by Talsidor** [comment]
Fixed this by adding an optional call to EndTargeting to InactiveInit. I've exceptioned this in the one place I found it cause another issue, which was when Tavian fires his sling. There may be other places where we'll have to add the new InactiveInit param to except the call, but I made it on by default as I think it's overall healthy to try to end targeting when the player is set inactive.
