### ISSUE TITLE
Convo: If waiting on a convo long enough the dialogue box disappears

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#102]
Repro:
Go to level "02-2-Sewer-TraningChamber"
Talk to the first dummy.
Wait approx 10 - 20 seconds.
The convo box will disappear

This can be confusing to anyone returning after stepping away as there is no prompts on the screen.

**Comment by Talsidor** [comment]
I waited over a minute on the first and second lines of the convo and also tried pausing-unpausing during the convo, and I couldn't cause this to happen. Can you demonstrate it to me tomorrow?

**Comment by Talsidor** [comment]
Issue was repro'd but seems to be a repeating quick convo interrupting the conversation. Tim will fix by making sure the repeater gets disabled when the convo starts.
