### ISSUE TITLE
Audio spiking on level transition

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#105]
The audio (music) seems to play much much louder after transitioning through a zone.
This was only observed going from the Tree Ext to the Tree Int.
Weirdly, the audio plays at normal volume after delving deeper into the level. 

Repro:
Start on Floor 4 of the tree Ext. (The level with the pressure plates and holdables.)
Enter the Tree and complete the pressure plate puzzle.
Take the first exit (the one on the right of walking through the Polto log door.)
This exit takes you out onto a small platform with a health pickup.
Re enter the tree and do not move.
The audio should now be much louder than when you were originally in the area.
If you move around the level, the audio levels seem to go back to normal after a short period"

**Comment by Talsidor** [comment]
I believe this was part of the big "3D audio sources for music" issue, either way it appears fixed now.
