### ISSUE TITLE
Playing windowed does not persist when loading new scene

### ISSUE THREAD

**Issue by Volanare** [CardboardKeep/Warden#106]
Repro: PAXAus build updated to Steam on 19/10/2015.

Started the game and used the options menu to lower my resolution and swap to windowed. At the end of the Intro Sequence, loading into the Fire Shrine reset the resolution to native, and set the game to full screen.

**Comment by Volanare** [comment]
Also! It happens if you die and reload at the start of a level.

Repro: plants killed me in the Sewer Canals, respawned and the same thing happened.

**Comment by Talsidor** [comment]
I can't replicate this in 0.9.161, but the windowed resolution does get reset on level load, so I've applied a fix for that. Marking as resolved.
