### ISSUE TITLE
Starting Cutscene Break

### ISSUE THREAD

**Issue by RabbitBrains** [CardboardKeep/Warden#109]
When Tavians dad talks to me before the flower fight he seem to sink half way through the ground and have no animation. The camera stays fixed in the cutscene shot where the dad was talking to me and then I can't get out. I mashed Y a couple of times when he was talking to me?

**Comment by Agilethief** [comment]
@RabbitBrains  Is this reproducible? I cannot cause this to happen.
I require more information regarding causing this to happen

**Comment by Talsidor** [comment]
Closing as no further information was provided.
