### ISSUE TITLE
Nyona Cutscene intiates without Tavian in The Shot

### ISSUE THREAD

**Issue by RabbitBrains** [CardboardKeep/Warden#110]
I was able to slide of the cliff just as the cutscene was starting and the consequently the cutscene had dialogue of tavian without him there. This isn't really a bug but it shouldn't happen?
![bug](https://cloud.githubusercontent.com/assets/10243487/10627739/f4a89e70-7808-11e5-97da-eacfcfd7a876.png)

**Comment by Agilethief** [comment]
This should now be fixed, but will need some double checking.

**Comment by Talsidor** [comment]
Confirmed fixed, closing
