### ISSUE TITLE
Flinching can break targeting the target

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#112]
When targeting, being hurt and thus flinching can cause the player to no longer be targeting the enemy.
I find this to be very frustrating and feel bad.

Repro:
Find an enemy.
Target them.
Take damage from the enemy. 
You will stop targeting the enemy.

Notes:
Sometimes it seems only the black bars disappear but the target remains locked on.
Other times it seems the player stops targeting completely.

**Comment by Talsidor** [comment]
lol whoops

**Comment by Talsidor** [comment]
Confirmed fixed in 0.9.161
