### ISSUE TITLE
Campfire at start of fireshrine level is lit on entry

### ISSUE THREAD

**Issue by justgimmeafknname** [CardboardKeep/Warden#114]
When entering the Fireshrine level, campfire is lit and useable but restarts the level

repro - go to fireshrine level, press Y on fire, this just takes you back to the start of the level

- note - this happens whether you talk to the sleeping creature first or not

**Comment by Talsidor** [comment]
This is a good bug report, thanks Rob

**Comment by jimbobrlw** [comment]
tim fixed this! checked it twice.
