### ISSUE TITLE
Shapeshifting to Tavian freezes Player

### ISSUE THREAD

**Issue by Volanare** [CardboardKeep/Warden#116]
"NullReferenceException: Object reference not set to an instance of an object
Player.GhostTargeting () (at Assets/-Warden/Scripts/Entities/Wardens/Player.cs:460)
Player.Update () (at Assets/-Warden/Scripts/Entities/Wardens/Player.cs:255)"

Shapeshifted to Tavian from Medeira or Bitt. Once transformed, Tavian stands still, and does respond to any input from the keyboard, mouse or controller. Can still be damaged by enemies (experienced knockback by Mudmen), but this did not allow me to move the character. Could not swap to another Warden either.

Repro:
- Playing in editor, from Mountain-Waterfall level (08-02)
- Used console command "tt" to spawn weapon, torch, and unlock all Wardens
- Started as Medeira, tried switching to Tavian. Bug occurred.
- Started as Medeira, swapped to Bitt. Then swapped to Tavian. Bug occurred.

Note that this has not been happening when swapping to either of the other Wardens.

**Comment by Talsidor** [comment]
Tim submitted this issue 5 days ago, but your name, description and repro steps are better so I'm keeping this issue =p

**Comment by Talsidor** [comment]
From #115 : 
NullReferenceException: Object reference not set to an instance of an object
Player.GhostTargeting () (at Assets/-Warden/Scripts/Entities/Wardens/Player.cs:460)
Player.Update () (at Assets/-Warden/Scripts/Entities/Wardens/Player.cs:255)

Repro:
Be Bitt
Be near a Bitt Pot and a Sling ring.
Have the target reticle over the Bitt Pott.
Shift into Tavian
Reticle jumps to sling ring.

Error is thrown, cannot move.
May be difficult to repro but had happen multiple times.

**Comment by Talsidor** [comment]
So this only happens with the custom ShiftCube that's had a SlingRing dragged underneath it. I'm still not sure why. Disabling the ShiftCube and putting a regular sling ring in this level has no issues. I suspected a missing WHeadHeight component but it's there, despite the error seemingly happening when trying to access the **head.pos** on the object. Grr. Will continue investigating.

**Comment by jimbobrlw** [comment]
So the sling ring in that level has a duplicate placed right on top of it.
http://imgur.com/YI4iUYz
is this intentional? when i delete one of them it fixes the issue.
@Agilethief @Talsidor

**Comment by jimbobrlw** [comment]
fixed the issue! changed the OnDestroy() to OnDisable() so that when its disabled its removed from the list of potential ghost targets.
