### ISSUE TITLE
Crouching on Pressure plate locks it down

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#118]
Crouching on a pressure plate keeps it in it's activated state even when you walk off it.

Repro:
Get a pressure plate
Get a vertical door
Ensure both do not have "Lock" ticked.
Attach the vertical door to the plate.
Walking onto the plate opens the door, and stepping off closes the door.
Walking onto the plate and crouching, locks the pressure plate and the door remains open.

Repro:
Get a pressure plate.
Ensure it's not set to lock.
Crouch on the pressure plate.
It will be stuck in it's activate position.

**Comment by jimbobrlw** [comment]
fixed this issue. basically added functionality to the pressure plates to check for a player collision and not count the number of player collisions, just check it as a bool.
