### ISSUE TITLE
Shift Sticks: Some angles slide very very slowly

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#119]
The shift stick when moved at some angles moves very slowly.
I think the shift stick box should move at a flat rate all the time.

Repro:
Level 05-5-Mine-PyramidPottPuzzles
Go to the first room with a shift stick.
Move it about.

You will see that at some angles the shiftstick does not move very nicely.

**Comment by Talsidor** [comment]
This is fixed!
