### ISSUE TITLE
Rotating Bitt pot puzzle lever not working

### ISSUE THREAD

**Issue by justgimmeafknname** [CardboardKeep/Warden#125]
switch at rotateing bitpot puzzle in the pyramid doesnt open the gate you need to get through

repro - play the rotateing bitpot puzzle (05-5-Mine-PyramidPotPuzzles) - flip switch that opens the gate

![bitpotpuzzle](https://cloud.githubusercontent.com/assets/13193794/12084649/8f0f9a54-b30a-11e5-9db0-5249f358d8d7.jpg)

**Comment by Agilethief** [comment]
I believe this is now solved.

**Comment by Talsidor** [comment]
Yep this is fixed!
