### ISSUE TITLE
Can jump ledge at flourish puzzle heading into forrest

### ISSUE THREAD

**Issue by justgimmeafknname** [CardboardKeep/Warden#126]
player can make the jump up the ledge you are meant to use flourishing to get past in forrest scene

repro - play 06-1-GreatTree-Forest - jump the ledge

![forrestjump](https://cloud.githubusercontent.com/assets/13193794/12084709/55899a36-b30b-11e5-8730-78634370eceb.jpg)

**Comment by Agilethief** [comment]
I believe I have fixed this now with the new Grove setup.

**Comment by Talsidor** [comment]
Yep, there is now poison here that prevents you from going across, plus a handy quick convo to hint the correct path to the player.
