### ISSUE TITLE
Attacking an enemy too fast can get it stuck red

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#127]
During Dave's playtest he had a dagger and spammed it on a needlenose.
The needlenose got stuck glowing red.

Repro:
Get a fast attacking weapon.
Find an enemy (Needlenose works well)
Spam attack against the needlenose.

If attacking fast enough the red effect will get stuck on and the enemy will be glowing red.

**Comment by jimbobrlw** [comment]
wasn't able to reproduce this one, tim said hes only seen it once. maybe too rare to chase up.
