### ISSUE TITLE
Light shaft flickering 

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#129]
![warden_22-1-2016-14 30 9](https://cloud.githubusercontent.com/assets/10218123/12501781/52660c78-c115-11e5-97ef-c1390f369120.png)

This will happen occasionally as a camera sweeps through a light shaft.
Seems to be related to HDR and camera effects

**Comment by Talsidor** [comment]
Resolving this as wontfix as it's A.) kind of out of our control, B.) extremely infrequent, C.) very minor in effect and D.) difficult to see a path of action towards resolving it.
