### ISSUE TITLE
Opening menu- didn't open but cut out sound.

### ISSUE THREAD

**Issue by Arkanti** [CardboardKeep/Warden#13]
After entering the Sewer Canals I tried to open the menu to reinvert my camera, but it just cut out all sound and no longer let me open the menu. Alt tabbing in and out fixes the sound but still can't access menu.

**Comment by Talsidor** [comment]
Not reproducible and no steps provided, and the event system Tim mentioned is likely to be fixed. I'll assume that or the GUI rework has removed this issue. Please resubmit if it happens again in the latest version or newer.
