### ISSUE TITLE
Stuck Holdable

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#131]
When picking up a holdable and taking damage, the holdable appears to get stuck to the player breaking the game.

Repro - Grove level - Upper tree.
The puzzle with pressure plates and holdables.
The second fruit, when trying to pick it up, allow the potshot to hit you.
The holdable gets stuck in your hand and you cannot continue.

**Comment by Volanare** [comment]
+1, have encountered this issue in the Town Hub.

Player is still able to walk around, context buttons behave as though player still holding the rock, but you cannot throw or drop it. Note that taking damage does NOT resolve this.

Note that death DOES resolve this.

Repro:
- Enter Hub from Sewers
- Pick up throwable rock from the area immediately outside
- Polto attack damaging you causes the rock to stick in the player.

**Comment by Talsidor** [comment]
Fixed this by making the player drop any holdables they might be carrying when hurt. I can't remember if it used to work like this and for some reason stopped working, but this is definitely the easiest way to solve the issue.
