### ISSUE TITLE
Taking damage while entering a transition zone allows player movement

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#132]
Taking damage while enter a transition zone allows the player to continue moving.

Repro
* Go to the Grove level.
* Find the transition zone on the tree next to a needlenose.
* Time entering the transition zone with being struck by an acorn.
* When hit you can move around with the stick again. You will still transition to another level.

**Comment by Talsidor** [comment]
While this won't fix being able to move after a flinch/flyback has actually caused the player to enter the zone, I've made the player become invulnerable while transitioning, so at least if they're hit after starting the transition they will remain unharmed, which is the issue at hand here. Given the other potential issue is unlikely, non-game breaking, and expected to be quite a difficult fix, I'm going to resolve this issue and consider the other an acceptable risk unless it's brought up again.
