### ISSUE TITLE
Weapons can be picked up over and over again

### ISSUE THREAD

**Issue by justgimmeafknname** [CardboardKeep/Warden#134]
the Y button prompt keeps reappearing after picking up a weapon, allowing you to fill the slots with the same weapon. seems to happen with every weapon i pick up

repro:
Find a weapon
Pick it up without moving the left thumbstick
Press Y to pick it up again

**Comment by Talsidor** [comment]
@justgimmeafknname I can't reproduce this, does it still happen? Which scene is it happening in?

**Comment by Talsidor** [comment]
This only happens if you don't have Steam open, meaning the Steam API can't initialize. Dependency will be removed as the API coupling is untightened, but as for this issue it is resolved.
