### ISSUE TITLE
Player sounds (such as footsteps) stop playing occassionally

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#136]
Repro: If you simply play through the game this is pretty much guaranteed to come up, but unfortunately there is no current reliable repro.

Suspicion: I'm guessing this has something to do with the Player grabbing one of their weapon's soapboxes as their own, but the times this seems to happen don't line up with when I would expect this issue to occur.

**Comment by jimbobrlw** [comment]
tried transitioning from the intro to the first shrine twice, the first time all the wardens sounds were not playing, the second only the roll and attack voice were not playing

playing with the volume slider on the actual audio emitter component made it work, as did changing warden

**Comment by jimbobrlw** [comment]
Can confirm that the Play function is being called on the soapbox when its not making a sound.

**Comment by jimbobrlw** [comment]
The issue was, on the soapbox agent, in the on level load it was taking the time since level load and not the regular time. fixed that, works fine now.
