### ISSUE TITLE
Kill command, double kills, locks player.

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#137]
When using the kill console command the player will after a short while from respawning. "Die" but not die correctly.
The player will lose all health and not be able to interact with things anymore. Sometimes the player loses the ability to move.

Repro:
Go to any level (preferably one with a convo or other GUZ)
Open the console and type kill in.
Upon respawning. Wait a short period. Try jumping, crawling or using a GUZ.
After a short period all the players health goes down and the ability to use GUZ's stops.

**Comment by Talsidor** [comment]
This is fixed!
