### ISSUE TITLE
If the player is sliding when a cutscene/convo kicks in, they can move during it

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#138]
Repro: 
Go the IntroSequence
Press slide repeatedly, so you're sliding when the Emperor's lockjaw pounce cutscene, or sparring intro cutscenes kicks in. You'll then be able to fully act during these cutscenes.

**Comment by Agilethief** [comment]
I suspect this can happen sliding into transition zones too.

**Comment by Talsidor** [comment]
This is fixed :)
