### ISSUE TITLE
Crouching is invulnerable to mud queen ring attack

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#139]
If you crouch when fighting the mud boss. It's ring attack moves right through you.

Repro:
Go to the mud boss scene.
Start the fight.
Crouch.
Wait for the ring attack to happen and hit the player.
It will pass right through the player.

**Comment by Talsidor** [comment]
Fixed by replacing the unhappy mesh collider on the ring attack prefab with a ring of box colliders
