### ISSUE TITLE
Reloading area reset all puzzle progress.

### ISSUE THREAD

**Issue by Arkanti** [CardboardKeep/Warden#14]
Leaving the Sewer Canals and coming back, all previously lit levers were dark and the central platform was back in its original position.

**Comment by Talsidor** [comment]
@Agilethief Let's discuss how we want to address this now that we have the flag system in.

**Comment by Agilethief** [comment]
I think the entire area should reset unless you have completed the puzzle.
Essentially a flag to control if it is completed or not, and if it is completed then the corkscrew is retracted all the way when you come in again.

**Comment by Talsidor** [comment]
I concur with Agilethief, the flag system handles this well. Closing due to consensus.
