### ISSUE TITLE
Secret passage is only one way

### ISSUE THREAD

**Issue by justgimmeafknname** [CardboardKeep/Warden#147]
secret passage above the wall on the left as you enter the last training dummy room lets you go through one way to above the sewer canals , but not back

Repro: jump on barrels to the left as you enter the last training dummy room, jump up and over the ledge and go through the doorway to the sewer canals, turn around and try to go back the way you came

**Comment by Talsidor** [comment]
I think we should remove the shortcut, which would solve all these issues in one fell swoop

**Comment by Talsidor** [comment]
Shortcut has been removed!
