### ISSUE TITLE
Player can get stuck in sewer adjunct

### ISSUE THREAD

**Issue by justgimmeafknname** [CardboardKeep/Warden#148]
By taking the secret passage to the right in the last training dummy room to the Sewer Adjunct, the player can get stuck as the gate is closed on the way out and there are no other ways out of the room other than the secret passage which cannot be reached after falling into the level

Repro: Jump to the secret passage above the wall in the far right corner of the last training dummy room, then proceed through to the sewer adjunct, fall down into the level and run up the ramp through to the doorway back to the sewer canals, on exiting you are stuck behind a gate that you cannot open

**Comment by Talsidor** [comment]
I think we should remove the shortcut, which would solve all these issues in one fell swoop

**Comment by Talsidor** [comment]
Shortcut has been removed!
