### ISSUE TITLE
Traversing to Sewer Adjunct through secret passage looks wrong

### ISSUE THREAD

**Issue by justgimmeafknname** [CardboardKeep/Warden#149]
When using the secret passage to the Sewer Adjuct from the last training dummy room, the player walk at a diagonal upward as it fades

Repro: jump to the secret passage above the right wall in the final training dummy room, continue through the doorway and as the camera fades the player takes a steep incline that looks a bit worng

**Comment by Talsidor** [comment]
I think we should remove the shortcut, which would solve all these issues in one fell swoop

**Comment by Talsidor** [comment]
Shortcut has been removed!
