### ISSUE TITLE
Camera clips through walls in puzzle to the Left of the gate house

### ISSUE THREAD

**Issue by justgimmeafknname** [CardboardKeep/Warden#150]
when in the circular room containing a trapped mote bundle and a puzzle, the camera clips through the walls and puzzle elements and player meshes (hair, hats, weapons, torch etc) flicker in and out of visibility at some angles

Repro: Enter the small circular room to the Left of the entrance to the gatehouse, run around and move the camera

**Comment by Talsidor** [comment]
Fixed last week with the Town Hub mesh changes
