### ISSUE TITLE
Needlenose Death feels like it gives very little feedback

### ISSUE THREAD

**Issue by justgimmeafknname** [CardboardKeep/Warden#151]
When killing a needle nose, it seems like the hit sound doesn't play and flash is missing or something.

Repro: Destroy a few needlenoses and see how it feels

**Comment by Agilethief** [comment]
It's true, on death they do not seem to spawn a hitflash nor do they make the drum beat. 
Investigating now.

**Comment by Agilethief** [comment]
Should now be resolved, a simple fix.
