### ISSUE TITLE
Hats knocked from the Player SOMETIMES have no gravity on them

### ISSUE THREAD

**Issue by Volanare** [CardboardKeep/Warden#158]
While playing the Steam Beta build on April 2, I noticed on two separate occasions that hats did not have gravity applied to them when they were knocked off the Player's head.

First time was in the Pyramid (I think it was in the Puzzle Chamber? Wherever you find the Mario Hat). A Tsarr attacked me and the hat fell off, but floated upwards without any gravity effecting it.

Second time, I was in the Grove Low. Had the Solaire hat on, as Medeira. Changed Warden, and the hat went flying off into the sky. Wept softly. If only I could be so grossly incandescent.

NOTE: I also had the pirate hat and several witches hats knocked off my head, and they did not float away. So yeah, there's that.

**Comment by Talsidor** [comment]
Fixed!
