### ISSUE TITLE
Player in falling animation on moving platforms

### ISSUE THREAD

**Issue by Volanare** [CardboardKeep/Warden#159]
When standing still on a platform that moves up and down, the player will go into the falling state/animation as the platform moves up and down.
I can't remember whether we'd just decided to leave this as it is. It wasn't game breaking, but did feel  a little "broken".

Repro: final platform in the Pyramid Puzzle Chamber. Stand on it when it's activated.

**Comment by Agilethief** [comment]
The first step is attaching a Kinematic Rigidbody with it's mode set to interpolate onto the moving platform.
This solves the ungrounding of the player.

The player will still jitter a little bit but it is much better.

**Comment by Agilethief** [comment]
I have gone through and applied this to everything I could find, however if it is seen again I will need to know which objects and where to be able to fix it.
