### ISSUE TITLE
Targeting letterboxing black bars don't go to edge in most aspect ratios

### ISSUE THREAD

**Issue by Volanare** [CardboardKeep/Warden#16]
When playing the game, if I use the left-trigger's targeting mode, the letterboxing black bars don't fully cover the screen. Will get a screenshot to display what I mean.

I'm running the game at 1440x900, full-screen, on my primary monitor.

**Comment by Talsidor** [comment]
*From #26 :*
![image](https://cloud.githubusercontent.com/assets/10220012/6185784/9101c916-b3c6-11e4-8ace-d7a4d3b338ca.png)

In the above image I have added an extra 1cm around the screen shot, so the hairline is clearer to see.
In game this is pretty obvious.

**Comment by Talsidor** [comment]
Fixed!

**Comment by psummerfield** [comment]
sweet! ;D I am just trying to replicate that menu sliding issue! ;)
