### ISSUE TITLE
First lore log doesn't appear in list

### ISSUE THREAD

**Issue by Volanare** [CardboardKeep/Warden#160]
[Note from April 2 Steam Beta play through]

First lore log collected does not appear in the list on the left-hand side.
NOTE: interacting with the Lore side list with a mouse will cause the lore log to appear.

Repro:
Collect your first lore log (one of the three in the Fire Shrine), 
Pause the game and navigate to the Lore menu.
First lore log does not appear in list.

**Comment by Talsidor** [comment]
Fixed with a workaround.
