### ISSUE TITLE
Player de-syncs from levers while in animation

### ISSUE THREAD

**Issue by Volanare** [CardboardKeep/Warden#161]
[From April 2 beta build on Steam]

When interacting with levers, the player will complete their animation (as will the lever), but the player will slide away from the lever - as though they're still moving. I spotted this continuing in a cutscene (player actually reverted to walking animation and walked away from the lever).

Repro: Factorum Windmill was where I first noted this. Also happened in Water Wing (this is where I spotted it in a cutscene)
Find lever at top of Windmill
Pull lever
Player will start to slide

[I'm not sure this will always happen, I only noticed it happening after the Factorum Windmill but it seemed to be happening every time after that]

**Comment by Agilethief** [comment]
Repro:
Windmill.
Jump on the edge of the wheel of the windmill. it is sloped and will start to slide you off.
As you slide pull the lever.
You continue sliding, but play the lever animation.

I'm going to freeze the players velocity when they use the lever.

**Comment by Agilethief** [comment]
I've applied a fix for this, keep an ear out and an eye aboot incase you see this again.
