### ISSUE TITLE
Holding rock during tentacle cut scene binds rock to players hand

### ISSUE THREAD

**Issue by jackknobel** [CardboardKeep/Warden#162]
**Reproduce Steps**
- Start New Game
- Talk to emperor to initiate vine cut down
- Pick up rock before the emperor cuts down the vines

After the cut scene finishes you are unable to drop the rock and cannot interact with any objects. 

**Screenshot**
![20160409130816_1](https://cloud.githubusercontent.com/assets/4241645/14401403/99421214-fe54-11e5-86f7-116748c85da9.jpg)

![20160409130758_1](https://cloud.githubusercontent.com/assets/4241645/14401404/af45c740-fe54-11e5-9c2b-a1f6f2d4f418.jpg)

**Comment by Talsidor** [comment]
This is now fixed, thanks Jack!
