### ISSUE TITLE
Enemies killed by other enemies count for the purpose of achievements

### ISSUE THREAD

**Issue by jackknobel** [CardboardKeep/Warden#163]
While reproducing the issue here: https://github.com/CardboardKeep/Warden/issues/162

I managed to unlock the achievement "Flora Fighter" without killing any plants and the achievement "Combat Novice" without killing well, anything!

On the other side of the river fellow soldiers are killing enemies, this seems to have triggered the achievements.

![achievementissue](https://cloud.githubusercontent.com/assets/4241645/14401430/be97edd0-fe55-11e5-9a04-cc1953f6ab96.PNG)

**Comment by Talsidor** [comment]
Fixed this today!
