### ISSUE TITLE
Health total increases after loading save file

### ISSUE THREAD

**Issue by Duhlan** [CardboardKeep/Warden#166]
Upon loading a save file the players health total is increased.

Re-loading the save file a second time I had nearly tripled my health total from 4 to 11.

![untitled](https://cloud.githubusercontent.com/assets/18360888/14402116/8c3de2e6-fe6d-11e5-8eca-821bc10d7ecc.jpg)

**Comment by Talsidor** [comment]
@Duhlan Hey Dylan, if you shut down the game entirely then re-open it and load your save file, are you back to the amount of health you should have?

**Comment by Duhlan** [comment]
Nope, health total appears to be at the maximum after quitting to system.
The first 3 times it happened I did only quit to the menu, not the desktop though, not sure if that tells you anything.

**Comment by Talsidor** [comment]
This has been fixed, thanks Dylan =)
