### ISSUE TITLE
First Polto fight enemies get knocked back through walls

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#169]
"SO my 'captors' keep glitching through the walls making the area impassable..."
http://steamcommunity.com/app/338310/discussions/0/365163686075733361/

**Comment by Agilethief** [comment]
I belive this to be fixed. 
I could not reproduce the initial polto fight getting stuck behind any walls.

**Comment by Talsidor** [comment]
"After the Sewer Canals
- The Captors can be pushed inside most of the walls & blocks in this area & they can't get back out, they can hit you but you can't hit them; so you have to re-enter the sewers in order to restart the fight."
http://steamcommunity.com/app/338310/discussions/0/365163686069814659/

**Comment by Talsidor** [comment]
There were a couple more objects they could clip through, I've adjusted these and _hopefully_ we won't see this pop up again.
