### ISSUE TITLE
Bench sitting bug

### ISSUE THREAD

**Issue by psummerfield** [CardboardKeep/Warden#17]
The new bench when you first enter the forest with the hollow tree. Once character sits on bench he either falls off automatically or can be pushed off with pushing forward on directional pad.
see images for examples.

either you can move charecter in sitting position till he falls off ledge and is standing up or game locks up and you need to re-start game. (save and quit)

![image](https://cloud.githubusercontent.com/assets/10220012/5516555/599e7a24-88fa-11e4-9857-146d832bdda9.png)
![image](https://cloud.githubusercontent.com/assets/10220012/5516559/63ecbd6a-88fa-11e4-9cc1-183c6da35e56.png)
![image](https://cloud.githubusercontent.com/assets/10220012/5516564/7990de30-88fa-11e4-9673-740f5016c50d.png)
![image](https://cloud.githubusercontent.com/assets/10220012/5516566/8313d570-88fa-11e4-9ef2-5ee9c89c8d77.png)

**Comment by jimbobrlw** [comment]
know how to fix most of it, but there's an issue with how the generic trigger system works for this specific instance. I'll comment the code so that Calum can take a look at it when he gets the chance.

**Comment by Talsidor** [comment]
This bench simply doesn't exist in the game anymore, so closing this issue :)
