### ISSUE TITLE
Final Boss Fight: Show stoppers

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#172]
Crystals stop spawning:

"the last boss fight won't drop enough crystals to destroy to kill them."
http://steamcommunity.com/app/338310/discussions/0/365163686076188852/

Nyona doesn't destroy the Emperor's shield:

"Come into a nasty bug now though. I'm on the final boss and decided to attack the emperor. I destroyed the crystals and got him to his third lhase of health but died after getting caught in one of the ground smash attacks. Now following this with each attempt I've made at fighting him destroying the crystals doesn't cause Nyona to destroy his shield." - Daryl from Use A Potion

Then switching to Nyona also has issues: 

"I tried fighting Nyona instead, and destroying her crystals does nothing either. I've quit the game, restarted the PC etc. But no luck. You encountered this bug? It's a frustrating one, cause it's stopping me from finishing the game." - Daryl from Use A Potion

**Comment by Agilethief** [comment]
The crystals were not cleaning up their list safely. This is now fixed.
This should fix restarting the fight not working too.
