### ISSUE TITLE
Pyramid Boss Fight: Voiding out, respawning and stairs issues

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#175]
From UnimaginativeHandle:
"if you get pushed off the platform you are spawning slightly too far in front of the entrance to the area & get a death loop, you can barely get back into the platform if you time a jump right but the stairs have de-spawned, so you have to exit the room & restart the fight. But if you lose all your health in the fight, then you respawn & the stairs are still there; weird bug that."

**Comment by Agilethief** [comment]
I believe this was caused by the player missing the checkpoint before the fight.
Causing the player to respawn below the now fallen stairs.

I can not reproduce this bug and I have increased the size of the checkpoint. 
I am interested if it comes up again.

**Comment by Talsidor** [comment]
Slightly different wording from the same guy
"if you get pushed off the platform by the boss, or fall off, you get caught in a death loop because you seem to spawn right near the edge of the entrance to the room at the bottom of the stairs.
You can barely get back onto the platform if you time a jump right, once you have spawned but it does no good seeing as the stairs aren't there anymore so you have to exit the room, making this battle something you have to flawless to progress."
