### ISSUE TITLE
Sliding quickly after Intro Seq combat tutorial causes sequence break

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#176]
"when the vines retract after the training with dad, if you slide or move too quickly toward the vines then you get the 'You are doing well, son' dialogue that is meant to occur after the Mud Men have spawned, but you don't get the Y prompt; so you have to restart the game."
http://steamcommunity.com/app/338310/discussions/0/365163686069814659/

**Comment by Agilethief** [comment]
I believe this was caused by hitting the next trigger zone by slidign through the vines.
I have preventing the vines from being slid through.

I could not repro this issues.
