### ISSUE TITLE
"Select Save" slots overlap at certain resolutions

### ISSUE THREAD

**Issue by psummerfield** [CardboardKeep/Warden#18]
The save / loading screen game saves currently overlap each other.

When using the controller, you can not select a game file to load. you can click with mouse and tile will appear dark green.
![image](https://cloud.githubusercontent.com/assets/10220012/5516588/699d2316-88fb-11e4-88b1-f8aa053caa26.png)

**Comment by Talsidor** [comment]
Gui has been completely rebuilt, this issue is now deprecated
