### ISSUE TITLE
Jump height is sometimes variable

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#181]
"In The Sewers, I can't get the boy to jump onto the cube that is movable. Help please."
http://steamcommunity.com/app/338310/discussions/0/365163686079758516/

**Comment by Agilethief** [comment]
"Also I figured out the jump height get lower when you change character for the first time. The only way to get back the original jump height is to die with Tavian and reload the game."

https://forum.speeddemosarchive.com/post/warden_melody_of_the_undergrowth_7.html#warden_melody_of_the_undergrowth_7

**Comment by Agilethief** [comment]
I did some tests altering the time scale.
At timescale;
0.1 = 0.2 height when jumping.
0.25 = .54 height when jumping.
10  =  7-10? height when jumping.
1 = 2? height when jumping.

Faster timescales were much harder to observe, however it is clear that the timescale is influencing the jump height.
I don't think changing Wardens is the cause for this problem, rather slowing down of the timescale during Warden changes or killing the final enemy is causing the jump to become less stable.

My proposed solution would be to go through the jump code and ensure that it works the same regardless of the timescale.

**Comment by Talsidor** [comment]
This should be pretty simple - I'll replace the Time.deltaTime calls with
Time.unscaledDeltaTime, and add in a safety to make sure after slow-mo the
time scale goes back to EXACTLY 1 (which is what I'm now thinking might be
the cause of the discrepancies).

**Comment by Talsidor** [comment]
Updating here from a few days work on Trello two weeks ago - the issue was frame rate dependent, not just time scale dependent, and wasn't easy to solve. 

The current solution is to let the player continue boosting until they've reached a jump height of 2. This doesn't stop the maximum possible jump height from being frame dependent, but it does ensure that regardless of frame rate, it will always reach at least 2 units, so all jumps in the game will be achievable. 

This is live in the beta build but not on the default branch yet, though a couple of hours playing with it it has seemed very reliable.

**Comment by Talsidor** [comment]
After a few more hours testing (and across different platforms) I'm confident of the stability of this fix.
