### ISSUE TITLE
Intel IGP: Crash after first Nyona dream

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#182]
"After sleeping at the campfire and talking to the dragon in the (presumably) dream 11 minutes in, a driver for my Intel HD 4000 integrated graphics card crashed. The game still runs, but I get no image. Can anyone help me that ran into the same problem?"

"I am having the same problem. Same grapics card. I updated the driver as you suggested and turned off all the options and reduced my screen resolution. It locks up and shuts down everytime I speak with the dragon after the fire scene. :("

http://steamcommunity.com/app/338310/discussions/0/365163686072493459/

**Comment by Agilethief** [comment]
As this is below spec I suggest we close and forget :P

More seriously, I can't see anything special about that transition, it is really one of the tamer level transitions to occur. 
This combined with the below spec leads me to think we should not worry about resolving this.

**Comment by Talsidor** [comment]
I couldn't replicate it on my MacBook Air, which is an Intel 5000 series
IGP, all the reports we've had of this are 4000 series, so even weaker.
(6000 series has also been out for quite a while)

Since we have no way of reproing it I concur, there's nothing we can
currently do, and it's way below our min spec.

**Comment by Talsidor** [comment]
Potential cause in case this is investigated again: The garbage collector is manually invoked at scene transition, there may be a bug between the Intel 4000 IGP and assets that are cleaned up at the end of the Nyona dream scene which causes a crash. Although we don't have solid information that confirms this actually happens at the _end_ of the scene.

Regardless, closing this issue as Intel 4000 IGP is not supported.
