### ISSUE TITLE
Merchant window hammer disappears if you quit the game without picking it up, players then consider themselves stuck

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#185]
"I got a game breaking bug that does not allow me to continue the game. I played untill the scout stands in front of a gate and a merchant throws a hammer out of a window at Mayor´s Manor. I did not pick up the hammer and left the game. I wanted to continue now, but the hammer is away. The merchant does not say anything. I can´t continue :("

http://steamcommunity.com/app/338310/discussions/0/361787186439893592/

**Comment by Agilethief** [comment]
I have resolved this.
