### ISSUE TITLE
Player knockback sometimes goes twice the distance

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#189]
"i think that the normal knockback is a little too far but sometimes when knocked back i skip and go twice the distance. this bug makes up 80% of my deaths"

http://steamcommunity.com/app/338310/discussions/0/#

I'm not sure what this is referring to, I don't think I've seen it before.

**Comment by Agilethief** [comment]
The link attached does not go to a steam discussion, but the Warden discussion page?

**Comment by Agilethief** [comment]
http://steamcommunity.com/app/338310/discussions/0/357284131786201897/
I believe this is the discsussion thread

**Comment by Agilethief** [comment]
I don't think there is enough information to repro here.
I have spent a few max health lives being hit by a few enemies and I don't see this double knock back effect happening.

Some enemies will only flinch you on some hits but properly flyback you on other hits. This might be what this person is feeling.

I move that we close this issue as there is no enough evidence to action upon.

**Comment by Talsidor** [comment]
Agreed
