### ISSUE TITLE
Mouse camera slows down over time in some levels

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#191]
"Can't believe this is still a thing in the game but basically when I do the forest part and start getting closer to the boss my camera eventually just breaks down to a point where I can barely move it using my mouse."

"So I looked at it a bit more and it also happens early on with the training mechanical thingies, after about the 2nd one and onwards it slows the camera down but is fine after loading, same goes for the forest part where in some areas it just breaks the camera down to be barely able to move it at all, worst is the 2nd to last room at the top before going outside then entering the boss room.

Turns out that if I disable Vsync and turn it back on it fixes it completely, with a controller it is perfectly fine but the mouse can still be completely broken and will barely move."

http://steamcommunity.com/app/338310/discussions/0/357285562495007557/

**Comment by Agilethief** [comment]
I could not reproduce.
I played through the spoken levels (except for the training room), generally had a frame rate ranging from 27 - 60 fps
The Vertical controls with the mouse did seem to slow down a little bit in all scenes after a while but that may simply be inaccurate. 
I tried killing myself repeatedly too and it did nothing.
