### ISSUE TITLE
Teleporting after Factorum boss game freezes on white screen

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#192]
"Entering the teleport circle right after the boss battle in the Factorium the game stopped with a white screen. I had to do the battle all over again. (Hard to tell if this is a real bug or an issue with my PC)"

Going to guess we can't repro this but wanted to check before dismissing it.

**Comment by Agilethief** [comment]
Tired twice, could not repro.
Tried killing self after activating teleport, did not repro.

Don't think there is anything we can do without more information regarding the issue.
