### ISSUE TITLE
Tsarr Duelists get stuck in wall - makes Duelist Room unprogressable

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#193]
"After the last campfire of the pyramid levels (where you have to shut off these energy field barriers), you happen to come into a room (kind of a labyrinth) where the door shuts after you enter. You have to defeat all the enemies there, before the doors open. But I accidentally managed to push one of the skeletons into the wall, and it did not come out again (you can hear it though)."

Should be fixable with some invisible boxes in the walls, but they could also be going past the doors, which may be harder to fix.

**Comment by Agilethief** [comment]
This would be much easier to resolve if a more specific part of the geometry was specified.

**Comment by Agilethief** [comment]
I believe I have solved this issue occuring. 
I have extended the door blocking nav obstacle to also block the side corridors that are very close to the outside, this should prevent the duelists from lunging through the walls and resolving the nav mesh onto the exterior of the room. 
Also added a safety collision box to the section as I fell through the level geo at one point (Was quite strange)
