### ISSUE TITLE
Holdables - Can damage player when walking past.

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#24]
Holdables can damage the player (or anything probably) when moving past the stationary holdabe.

Reproc:
Find some holdables sitting on the ground (Ring of rocks in Polto village)
Move in and out of the ring.
This should cause you to get damaged.

Alt:
Standing on one rock, try walking across to other holdabes.
The ensuing collision seems to register enough velocity to cause the player to take damage.

**Comment by Talsidor** [comment]
Fixed, simply increased the threshold at which damage is dealt. This was tried before and wasn't as simple, I believe PhysX 3.3 may have helped here.
