### ISSUE TITLE
pause game screen not loading correctly

### ISSUE THREAD

**Issue by psummerfield** [CardboardKeep/Warden#25]
I am using new patch, with keyboard and mouse.
![image](https://cloud.githubusercontent.com/assets/10220012/6185669/57e06dfa-b3c5-11e4-95ab-620b0599ff4e.png)

When pressing ESC to get to book/pause area(above picture), instead of the book staying in place, it slides back out of screen and reverts to a still image of the game. press the esc key again and it reverts back to normal play. this happened over and over again till i restarted the first level.

**Comment by Talsidor** [comment]
@psummerfield This is not reproducible on our end so we need more information. Which level was this in? Which Warden were you? What had you been doing before this happened? Was there a point where it *did* work?

**Comment by psummerfield** [comment]
Hey. I'll give it another go Tonight. I'll try for more informative descriptions.

**Comment by psummerfield** [comment]
is there any way default way on win8 to capture video of screen. Similar to screen shots?
Any simple  screen capture software you can recommend?
Being able to capture glitches as they happen, would make life easier.  :)

**Comment by Talsidor** [comment]
@psummerfield No default OS way that I know of, I recommend OBS (https://obsproject.com/), we use it for all our recordings.

**Comment by Talsidor** [comment]
@Agilethief has reproduced this in the build on his end, but I've yet to reproduce it in the editor, so more info would still be good.

**Comment by Talsidor** [comment]
I implemented a suspected fix for this and haven't seen it since. Closing but if repros are found please submit a new bug.
