### ISSUE TITLE
letter box targeting slight adjustment needed to edges

### ISSUE THREAD

**Issue by psummerfield** [CardboardKeep/Warden#26]
![image](https://cloud.githubusercontent.com/assets/10220012/6185784/9101c916-b3c6-11e4-8ace-d7a4d3b338ca.png)

In the above image I have added an extra 1cm around the screen shot, so the hairline is clearer to see.
In game this is pretty obvious.

**Comment by Talsidor** [comment]
Closing as this is a duplicate of #16
