### ISSUE TITLE
force crawl not working / head going through tunnel roof

### ISSUE THREAD

**Issue by psummerfield** [CardboardKeep/Warden#27]
![image](https://cloud.githubusercontent.com/assets/10220012/6185879/6aa36512-b3c7-11e4-97bb-91f90c79217b.png)
Perhaps make the doorway higher?
;D

**Comment by Talsidor** [comment]
@psummerfield Can you confirm which level this is?

**Comment by psummerfield** [comment]
Yeh sure sorry. First level. secret flower battle inside tree entrence.

**Comment by psummerfield** [comment]
I'll check before posting bug reports and minimize the duplicates.

**Comment by Talsidor** [comment]
@psummerfield I just tried for 15 minutes and can't reproduce this in the same location. Would love a video if you can.

**Comment by psummerfield** [comment]
i also tried and couldnt replicate it. I did play with trying to get a weapon in de-bug menu, so i am sorry, i might have bugged it accidently. ill play with only getting lanterns to find bugs.

**Comment by Talsidor** [comment]
Closing this now as no reproducibles, feel free to open a new issue if repro is found.

**Comment by psummerfield** [comment]
no probs, I coudnt replicate it again either. ;)
