### ISSUE TITLE
Mudmen are not damaging the player.

### ISSUE THREAD

**Issue by psummerfield** [CardboardKeep/Warden#31]
After breaking my weapon i had to fight the mudmen without a weapon, so like any good Roman i kicked it.
Mudman didnt give me any damage from its hits and eventually got stuck in the wall and pushed me through the level. i died and kept re-spawning below the level mesh to fall to my death over and over.

image is straight after re-spawning
![image](https://cloud.githubusercontent.com/assets/10220012/6186230/ed38a048-b3ca-11e4-9a62-dde359a7f8b4.png)

**Comment by psummerfield** [comment]
This was the first mudmen encounter. I'll  try to do it again

**Comment by Talsidor** [comment]
This is fixed, the Mudman now hurts the player again. @psummerfield If you can provide more information on exactly where he knocked you through the wall we can look at fixing that too.
