### ISSUE TITLE
Intro Sequence - die then void out keeps checkpoint, breaks flow

### ISSUE THREAD

**Issue by psummerfield** [CardboardKeep/Warden#34]
After getting to the mud men in the intro level I died, and respawned with old Roman saying pickup the sword and bash the vines. But instead i jumped in the river.

I re-spawned where the bridge with the cart and the door that doesnt open. without a sword or a way to get back to the old man to get a sword and unable to cross bridge.

Jumping in river doesnt help and keep respawning back to this empty area.

ps, are the mouse and keyboard controls working ok for you guys? its almost impossible to control camera with mouse for me.

**Comment by Talsidor** [comment]
@psummerfield When you say "But instead i jumped in the river.", where exactly was it you managed to jump in the river? We tried to cordon it off completely.
Please submit a separate issue for your PS.

**Comment by Talsidor** [comment]
![](https://images.bigcartel.com/bigcartel/product_images/158702449/max_h-1000+max_w-1000/bug-respawn-double-respawn.jpg)

**Comment by jimbobrlw** [comment]
on a related note, i noticed if you die to the potshot and after respawning kill it, it totally breaks the scene. the emperor wont progress through the small cave and the mudmen wont spawn.
![2015-05-28_00001](https://cloud.githubusercontent.com/assets/12590123/7852901/06d5ee64-0549-11e5-81ea-bcbd8db147c2.jpg)

**Comment by Talsidor** [comment]
This doesn't seem to be possible any more, but if the player dies to the mudmen they do respawn with their sword, making it easy to break the sequence by attacking the first vines. Will add an empty inventory trap at the player's spawn.

**Comment by Talsidor** [comment]
Fixed that too
