### ISSUE TITLE
training dummy freeze up in sewer training chamber

### ISSUE THREAD

**Issue by jimbobrlw** [CardboardKeep/Warden#35]
If the player attacks the training dummy before the cut scene starts, it appears he can continue attacking the dummy while it plays. if you hit the dummy with the third attack in the combo, it appears to kill the dummy and the cut scene camera doesn't know what to do, freezing the game.
![2015-05-26_00001](https://cloud.githubusercontent.com/assets/12590123/7804301/2c6456da-03a4-11e5-8f0e-0d4b8d214a8b.jpg)

**Comment by jimbobrlw** [comment]
just happened again on the third training dummy
![2015-05-26_00002](https://cloud.githubusercontent.com/assets/12590123/7804388/c9a750f4-03a5-11e5-90f3-6b9e6618e3cb.jpg)
this time i didn't kill the dummy, but the slow my initiated while i was talking to him.

**Comment by Talsidor** [comment]
Player can no longer break out of convo/cutscene inactivity by attacking. Fixed.
