### ISSUE TITLE
Load save issue, Life bar increase every time save is loaded

### ISSUE THREAD

**Issue by jimbobrlw** [CardboardKeep/Warden#37]
the number of life bars you have seems to go up by the number of extra life bars you have (if you have 4, it will increase by 1. 5, it will increase by 2 and so on..)

![2015-05-26_00003](https://cloud.githubusercontent.com/assets/12590123/7804505/63f41362-03a7-11e5-8da7-4c765a578bb0.jpg)
image: i loaded a save after collecting the first health pickup

**Comment by jimbobrlw** [comment]
this also appears to happen when you start a new game
![2015-05-26_00004](https://cloud.githubusercontent.com/assets/12590123/7804535/ccc26650-03a7-11e5-8e95-c4341e4b673c.jpg)

**Comment by Talsidor** [comment]
Can no longer replicate, assumed fixed somewhere along the way.
