### ISSUE TITLE
Shuntable Objects: Blocks can be pushed through walls

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#40]
**Repro Steps:** Find any regular shuntable (like the two boxes in the Sewer Canals) and push it towards a wall until it goes through it.

I'm fairly sure I know why this is happening, a regular shuntable is parented to the player while it's being moved which means the Player's CharacterController is in charge, but since the shuntable just has a regular collider the CC doesn't care what happens to it.
What I'm less sure about is why the shuntable's Rigidbody isn't resolving this by having a fit until it gets out of the wall. My only guess is the CC is suppressing the RB.

**Suggested Solution:** During my experimentation re-writing the shuntables for the eleventeeth time last week, it seemed placing CCs on the shuntables themselves resolved this. I opted for the more known solution in the meantime but this may be a path to stability.

**Comment by jimbobrlw** [comment]
ALL HAIL THE NEW SHUNTING SYSTEM
