### ISSUE TITLE
Meretian Soldier Head IK staying on after death again

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#41]
**Repro steps:** Fight and kill a Meretian Soldier. His corpse-face will continue to watch you as you murder his friends.

**Suggested solution:** This has happened before, it's likely an issue with HeadIKOff() either not getting called at all or getting called at the wrong time (followed by something that re-enables head IK).

**Comment by jimbobrlw** [comment]
looks like the this issue can be fixed by adding a line to the update function setting the target to null if the isDead function is true.

**Comment by Talsidor** [comment]
@jimbobrlw Can we resolve it outside of update so it isn't happening every frame? For example setting the target to null in the Die function.

**Comment by jimbobrlw** [comment]
@Talsidor yeah that works fine, chucked it in the Meretian Soldier Script under the Die() function, works like a charm.
