### ISSUE TITLE
Character able to move when should be stuck to a wall switch

### ISSUE THREAD

**Issue by jimbobrlw** [CardboardKeep/Warden#42]
the wall switch just before the mud golem in the sewer canals allows you to move while pulling it.
![2015-05-27_00003](https://cloud.githubusercontent.com/assets/12590123/7830229/1fae3f56-048e-11e5-97fe-321210c1fd50.jpg)

**Comment by jimbobrlw** [comment]
the generic use trigger's player freeze length is ser to 0.1, set it to the length of the animation and it should be fine.

**Comment by jimbobrlw** [comment]
the switch can also be reactivated after being activated for the first time, adding a set objects active trap to the generic use trigger and setting the object to inactive fixes all issues.

the switch is also correctly reset after the player dies.

**Comment by Talsidor** [comment]
@Agilethief Can you set the player freeze length on the wall lever prefab to the animation length? Also do we want a custom script for these like the regular lever has or are we happy to keep using a Generic?

**Comment by Agilethief** [comment]
@Talsidor This is fixed.
Using the generic trigger works well. I'm happy to continue using it.
