### ISSUE TITLE
Weapons: Stay in hand but treated as sheathed after certain actions

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#47]
Repro steps: The most noticable/reliable place to do this is with the wall lever in the Sewer Canals. Equip a weapon, pull the wall lever, then try to attack. Also notice if you press the button associated with that weapon it will draw rather than sheathe, despite being in your hand.

**Comment by Talsidor** [comment]
Possible triggers mentioned by Tim: Taking damage, entering a balance zone, climbing/ledge use or any kind of level use.

**Comment by Volanare** [comment]
Description below from duplicate #54 
"New Convo system (implemented end of May 2015) causes the player to unequip whichever weapon they're holding.

Note that although the weapon is not equipped, it is still shown in the player's hand. So you can't attack with it.

Not sure if this is an issue with GenericUseTriggers (which are now what trigger convos), or the convos themselves."

**Comment by Talsidor** [comment]
Inventory system re-write may have fixed this, if someone wants to test and confirm.

**Comment by jimbobrlw** [comment]
Ive seen this before and couldn't recreate it today, looks fine for now
