### ISSUE TITLE
Warden Switching: Hangs at point where Warden should switch

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#55]
When switching Warden the Warden hangs at the point that it should change Warden.

The console command is where this was first noticed but it should be noted the command functions and triggers the switch which implies that it is an issue with Warden switching in general.

Repro:
~ to access console
"SwitchWarden 0" or "SwitchWarden 1" to change Warden.

You should see the Warden float up and hang at the apex, timescale will also slow down.
It will never change.

Suspected Repro:
Find a Warden Spirit and switch with it.

**Comment by Talsidor** [comment]
Fixed, but has revealed issue #59
