### ISSUE TITLE
Can see the warden while in first person mode 

### ISSUE THREAD

**Issue by jimbobrlw** [CardboardKeep/Warden#56]
![i can see my ears](https://cloud.githubusercontent.com/assets/12590123/7999465/c24184ce-0b8e-11e5-8b91-060fa94e79a7.jpg)
i think this is something to do with the warden not being on the player layer, not really sure how to set this for all instances of the prefab though.

**Comment by Agilethief** [comment]
Yeah this one will come up a lot as everytime we need to reimport the rig for the player we need to set all the mesh to the Player layer. I've given myself a card and will resolve this once it's done.

**Comment by Agilethief** [comment]
I've now corrected this, but it may pop up again if we alter the character rigs.
