### ISSUE TITLE
Sword plant doesnt have sword and is invincible.

### ISSUE THREAD

**Issue by psummerfield** [CardboardKeep/Warden#60]
![warden_16-6-2015-14 7 29](https://cloud.githubusercontent.com/assets/10220012/8175698/76dd12d6-1431-11e5-8b0b-6cf685a1fa0a.png)

Upon re-entering first main chamber with the water wheels, this sword plant doesn't have sword and was invincible. needs another few breakthroughs to see if this happens again! ;)

**Comment by Talsidor** [comment]
Fixed
