### ISSUE TITLE
Void Zone kills player without having "Kill Player" flagged

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#65]
Repro: Load or spawn into the Intro Forest / Fire Shrine level. Jump into the water. Player will fully die.

Intended: Player should "void out" instead.

**Comment by Agilethief** [comment]
You shouldn't be able to get into the water at all now in the intro seq.
If you could then it should completely kill you causing the level to reload to prevent any sequence breaking.

In the fireshrine it should be set up with a deathzone (aka void zone) and afaik that should only void the player out.

@Talsidor 
I was under the impression that if it was not death from damage then it was always voiding out

**Comment by Talsidor** [comment]
@Agilethief This isn't related to what that specific area should do but what void zones are in fact doing. The Void Zone there doesn't have killPlayer ticked so it shouldn't be killing the player. Repro was just the place I noticed it happening.

**Comment by Talsidor** [comment]
Not sure what was causing this but I can no longer reproduce it in the above scene or a test scene. Assumed fixed.
