### ISSUE TITLE
Hats disappear when switching Wardens 

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#67]
Repro: 
Get a hat
Switch Warden
Switch back
Your hat will now be gone

Question: Should hats be Warden specific? Or carry between them?

**Comment by Talsidor** [comment]
This needs to be discussed and decided before it can be acted upon

**Comment by Talsidor** [comment]
Hats now fall off your Warden when you switch, allowing you to pick it up again with the new one. Closing this as I consider it resolved, feel free to re-open if it's still an issue.
