### ISSUE TITLE
Push box into wall - recieve infinite amount of velocity, not removed by hurting or dying

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#68]
Repro: Grab the first pushable box in the Sewer Canals and push it into the wall, warden will be launched off the box and probably into a corner of the map, where you can no longer move due to the insane amount of force being applied to you. Hurting or killing self does not cause force to be reset.

Intended: Pushing a shuntable into a wall shouldn't apply an enormous force to the player, nor should that force remain after death.

**Comment by jimbobrlw** [comment]
PUSHING IS DEAD!!!
