### ISSUE TITLE
Bloom/DoF/AA Boxes Not Ticking/Unticking

### ISSUE THREAD

**Issue by Volanare** [CardboardKeep/Warden#69]
(This bug occurred in an AIS build, R3 on 03/07/2015. When I tried playing in the editor on 06/07/2015, the issue did not reappear)

When going into the pause menu to tweak visual settings, I noticed that the boxes for Enable Bloom, Depth of Field and Anti-Aliasing were already unticked. I tried ticking these boxes (with the mouse), and while the button would highlight when I moused over it, clicking it would not tick the box.

Given the performance change after clicking these boxes, I believe the effects were still being applied/disapplied.

**Comment by Talsidor** [comment]
I suspect this has long been fixed, if anyone can check and confirm.

**Comment by Talsidor** [comment]
Can't replicate this in editor or build on 16 March 2016, marking as resolved.
