### ISSUE TITLE
player sometimes freaks out after pulling levers

### ISSUE THREAD

**Issue by justgimmeafknname** [CardboardKeep/Warden#71]
i noticed this in the sewer adjunct

**Comment by Talsidor** [comment]
"Freaks out" isn't a very quantifiable issue, although thanks for including the area but more repro should still be added; for example does it happen during the lever pull animation? Immediately afterwards once? Continuously for the rest of the level/game after that point? Is it only on pulls or also on pushes? You said it happens "sometimes" but is there anything that makes it more or less likely?

**Comment by Talsidor** [comment]
@justgimmeafknname You never provided more information on this issue and I've since done a bunch of work on the levers. If you want to report it again file a new issue with a better description.
