### ISSUE TITLE
Cranks use zone is sticky

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#75]
Cranks can be used even when you walk away from them.

Repro:
Find a crank.
Walk into the crank's zone
Push the crank around a little bit
Walk away from the crank
You should still be able to crank the object.

**Comment by psummerfield** [comment]
This is similar to the light the fire action...which was in the last build.

**Comment by jimbobrlw** [comment]
could be related to specific braziers/cranks, could be an instance where certain things cause the using object to not drop off like it usually does.

Ill take a look!

**Comment by jimbobrlw** [comment]
new crank system should have fixed any non crank specific issues
