### ISSUE TITLE
Struck while going into crouch. Can no longer move 

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#77]
Repro:
Find a needle nose
As it's projectile is about to hit you, crouch.
This should lock your ability to move (Can't do anything but move the camera)

**Comment by jimbobrlw** [comment]
it sets the state to inactive, it also works with attacking.

**Comment by jimbobrlw** [comment]
threw in a hack fix for this for now.
added an idle time to the inactiveinit() function so the player cant get stuck in the inactive state.
ie: InactiveInit("animTrigger?", "Flinch","idleTime?",1);

**Comment by Talsidor** [comment]
@jimbobrlw I'd like you to brief me on this tomorrow

**Comment by jimbobrlw** [comment]
FIXED! flinch now forces the flinch animstate
