### ISSUE TITLE
Mudmen can knock the player through walls

### ISSUE THREAD

**Issue by justgimmeafknname** [CardboardKeep/Warden#79]

**Comment by jimbobrlw** [comment]
Looks like the player can be smashed through mesh colliers by mudmen.

**Comment by Talsidor** [comment]
Potential repro (which was in the original title but removed by James): Stand up against the giant door at the end of the IntroSequence level, player can be pushed through it via Mudmen attacks.

I've replaced the mesh collider on that door with a box collider to just alleviate one potential location this bug occurs.

**Comment by Talsidor** [comment]
Whether it was a Unity/PhysX version upgrade, changes in the Mudman's natural weapons, or changes in the player's movement and colliders, this seems very stable now. Closing as resolved!
