### ISSUE TITLE
Intro Seq Potshot Convo can't continue from.

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#85]
Playing through the intro sequence.
The conversation that you are forced to have with the emperor via trigger zone seems to lock up and stop the player from continuing on.

Repro:
Jump into intro seq
Play through to the potshot. 
Activate the convo via the trigger zone.
You will not be able to press Y to end the convo.

I have not checked if talking to the emperor first will dodge this.

**Comment by jimbobrlw** [comment]
wasn't able to recreate this one, might have been fixed.
