### ISSUE TITLE
Flourish Flowers: Press sheathe weapon while flourishing a flower gets the player stuck

### ISSUE THREAD

**Issue by Talsidor** [CardboardKeep/Warden#89]
Repro: Be Medeira, target and use flourish power on a flower, while flourishing sheathe the currently held weapon. Player should become permanently stuck (open and close console to unstick).

Lead: The flourish animation is weird in general right now, and gets stuck on a lot of the time. It's not set up as well as it could be. I suspect this is also causing the stuck issue.

**Comment by jimbobrlw** [comment]
fixed this issue, made the flourish channel a co-routine and added a bool that weapon equipping, sliding and attacking from happening while the player is flourishing.
