### ISSUE TITLE
Motes on Sewer Canals ledge aren't collectable

### ISSUE THREAD

**Issue by RabbitBrains** [CardboardKeep/Warden#9]
Glowy globs on the ledge that you first grab and hang across doesn't absorb into you when you go past.Stays there forever uncollected.

**Comment by Talsidor** [comment]
*From #30 :*
![image](https://cloud.githubusercontent.com/assets/10220012/6186121/b89443de-b3c9-11e4-8695-7d462eda0d01.png)
The green balls of energy were not able to picked up while climbing across rail.

**Comment by Talsidor** [comment]
We can't reproduce this, if it happens again to anyone can you please check if you can collect them by jumping into them or another action? @psummerfield

**Comment by Talsidor** [comment]
Not reproducible
