### ISSUE TITLE
Bitt Pot through walls

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#91]
Bitt can target fire funnels through walls, then leap into them. 
This would allow the player to move out of bounds and very much breaks sequences. 

I would suggest targeting through walls be removed or limited in some fashion.

Repro:
Load up level "05-5-Mine-PyramidPotPuzzles"
Try to target each pot through the wall from each Pot.

Alt Repro:
Place a large cube taller and longer than the player.
Put a pot on the other side of it.
Try and target and use the pot through the wall.

**Comment by Talsidor** [comment]
Fixed! Player can't target anything through level geom now
