### ISSUE TITLE
Transition Zones - Walk in Circles

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#92]
Transition zones appear to cause the Warden to walk to a weird spot.
When walking into a transition zone, the Warden will walk towards the center of the zone, pass it and turn around. (Walking back the way they came instead of further into the zone)

This behaviour looks bad  and unpolished.

Repro:
Walk into a transition zone
Observe the movements of the Warden.

Was produced in the mine levels, may be unique to their transition zones (placement perhaps?)

**Comment by jimbobrlw** [comment]
moved to https://github.com/CardboardKeep/Warden/issues/93
