### ISSUE TITLE
First person mode camera rotates funny

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#95]
Going into first person mode rolls the camera when it should only yaw and pitch the camera.
Feels very odd to use.

Repro:
Any scene.
Go into first person mode.
Look around.

**Comment by jimbobrlw** [comment]
added this to issue 93
https://github.com/CardboardKeep/Warden/issues/93

**Comment by jimbobrlw** [comment]
looks like this is working fine now
