### ISSUE TITLE
Fall through hole in Fire Shrine

### ISSUE THREAD

**Issue by Volanare** [CardboardKeep/Warden#96]
Have discovered a spot on the path, right next to the first camp fire in the Fire Shrine, where Tavian will fall through the floor if he stands on it. Curiously enough, if you run over it you'll dip into the floor but keep going.

Repro: 
see image below. Just a few steps in front of Tavian is where it happens.
Playing in-editor, if that makes a difference.

![secret hole through the floor](https://cloud.githubusercontent.com/assets/10218762/9708000/f32bcc34-5558-11e5-88fe-7a7fce046f46.png)

**Comment by jimbobrlw** [comment]
It looks like all the Shrub_01 and Shrub_02 prefabs are zeroed out to this location, which is world 0. then the actual models are moved around the scene.

Either one of the collider is bugging out (i cant see any settings that are different for any of them) or layering 100 collider on top of each other causes issues.

**Comment by Agilethief** [comment]
I have removed the offending shrubs and cleaned up another potential cause for it (old level geometry was sitting there.)
Should now be fixed, don't seem able to repro anymore.
