### ISSUE TITLE
Weapon intersecting level Geo throws error

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#97]
If a weapon is placed in the engine halfway through the ground. When you run the game it will throw an error with it's soapbox manager.

I suspect it is registering the collision with the ground and trying to use the soapbox before the soapbox has finished setting itself up.

Repro:
Go to any level
Drag a weapon into the level.
Place the weapon so it is halfway through the ground.
Run.
You should get an error on the weapon complaining about it's soapbox.
Stop the game
Place the weapon above the ground, not colliding with anything.
Run.
The weapon should work perfectly.

**Comment by jimbobrlw** [comment]
@Agilethief Looks like this one only happens when the object is intersecting an object while the "stuck" tickbox on the weapon is unticked. could the error just be that you missed ticking that box?

**Comment by Talsidor** [comment]
Fixed by replacing the Destroy(gameObject) call in a dummy "replace at runtime" Soapbox Manager with a DestroyImmediate call.
