### ISSUE TITLE
Animations from convos continue playing after the convo, causing other animations to wait

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#98]
Repro:
Go to level 01-0-IntroSequence.
Talk to the emperor.
On the section where the emperor moves to the vines to cut them, he slides instead of walking.

This is caused due to the animation controller still being in the talk animation. 
In many cases I can see us actually wanting the animation to continue after the convo is done, however in this case it needs to be ready to continue walking as soon as the convo is finished.

**Comment by Talsidor** [comment]
In the case of this one animation on the Emperor, I've just reined in the exit time and brought the exit forward as the animation goes a lot longer than it needs to. In my eyes at least this one situation is a lot better now.
Given we may want the functionality to stay as it is in other situations I'll close this issue.
